spring:
  application:
    name: spring-boot-gitflow-demo
  
  # Database Configuration (H2 for demo)
  datasource:
    url: jdbc:h2:mem:demodata
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # H2 Console (for development)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: NON_NULL

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

# Custom Application Properties
demo:
  environment: ${DEMO_ENVIRONMENT:local}
  version: ${DEMO_VERSION:1.0.0-SNAPSHOT}

# Logging Configuration
logging:
  level:
    com.example.demo: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"