# UAT Environment Configuration
demo:
  environment: uat
  
logging:
  level:
    com.example.demo: INFO
    org.springframework: WARN
    org.hibernate: WARN

spring:
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false